---
- name: Install configure deploy docker container with war file
  hosts: docker
  become: yes
  become_user: ansadmin
  tasks:
#  - name: Stop a container
#    docker_container:
#      name: compledoker:latest
#      state: stopped

  - name: remove docker container
    docker_container:
      name: completedoker:latest
      state: absent
      
  - name: remove docker image
    docker_image:
      name: completedoker:latest
      state: abesent
      
  - name: create build directory
    file:
      path: /opt/ansible/docker/tomcat
      state: directory
      owner: ansadmin
      group: ansadmin
      mode: '0775'
  - name: copy Dockerfile
    copy:
      src: ./Dockerfile
      dest: /opt/ansible/docker/tomcat/Dockerfile
      owner: ansadmin
      group: ansadmin
      mode: '0644'
  - name: copy war file
    copy:
      src: ./webapp.war
      dest: /opt/ansible/docker/tomcat/webapp.war
      owner: ansadmin
      group: ansadmin
      mode: '0644'
  - name: build docker image
    docker_image:
      name: completedoker
      state: present
      path: /opt/ansible/docker/tomcat/
      tag: latest

  - name: Create a docker container
    docker_container:
      name: completedoker:latest
      image: completedoker:latest
      ports:
        - "8080:8080"
