---
- name: Install configure deploy docker container with war file
  hosts: docker
  become: yes
  become_user: ansadmin
  tasks:
  - name: Create a image based on Dockerfile
    shell: docker build -t compledoker .
  
  - name: Stop a container
    docker_container:
    name: compledoker
    state: stopped
    
  - name: remove container
    docker_container:
    name: compledoker
    state: absent
    
  - name: create build directory
    file:
      path: /root/completedocker
      state: directory
      owner: ansadmin
      group: ansadmin
      mode: '0775'
  - name: copy Dockerfile
    copy:
      src: ./Dockerfile
      dest: /root/completedocker/Dockerfile
      owner: ansadmin
      group: ansadmin
      mode: '0644'
    
    
    - name: copy completedocer playbook
    copy:
      src: ./webapp/target/*.war
      dest: /root/completedocker/*.war
      owner: ansadmin
      group: ansadmin
      mode: '0644'  
  - name: copy completedocer playbook
    copy:
      src: ./complete_playbook_docker.yml
      dest: /root/completedocker/complete_playbook_docker.yml
      owner: ansadmin
      group: ansadmin
      mode: '0644'
      
  - name: build container image
    docker_image:
        name: compledoker:v1.0
        build:
          path: /opt/completedocker
          source: build
        state: present
    
  - name: run docker image
    shell: docker run -d --name valaxy_demo -p 8080:8080 compledoker:v1.0
    
#   - name: run docker image
#    shell: docker run -d --name valaxy_demo -p 8080:8080 kumaricss1/{{ JOB_NAME }}:latest   
